[firebase]
apiKey = "AIzaSyBOmuWPMG4zLWRzXqAlK0ajie1sVIL1gzM"
authDomain = "vrhinow-blog.firebaseapp.com"
projectId = "vrhinow-blog"
storageBucket = "vrhinow-blog.appspot.com"
messagingSenderId = "54834288727"
appId = "1:54834288727:web:0b1e9879d8d9b77b3eeb12"

[article]
# ... andere Artikel-Einstellungen

# F체gt die 'Likes'-Funktionalit채t im gesamten Blog hinzu.
showLikes = true

# Optionale Einstellung: F체gt die 'Views'-Funktionalit채t hinzu.
showViews = true 